### PR TITLE
Implement Weather Map & Wind Direction Indicator

### LINKED ISSUE #76: BUG: Weather info not being displayed
## After the merging recent PR by @PriyanshuValiya, the weather info is not being reflected in the forecast cards. @PriyanshuValiya, can you look into it?

### PR DESCRIPTION
**Pull request by soni-shashan**
@Vatsal2054 kindly review pr
closes #76 and #78 
image
image
image
image

### CODE REVIEW

**Comment by soni-shashan** [comment]
closes #80

**Comment by soni-shashan** [comment]
@Vatsal2054 please  give me level 4 as i solve bug, level 3(weather map) and level 1 for(Implement Wind Direction Indicator)

**Comment by Vatsal2054** [comment]
@soni-shashan The map box is too wide, make it a rectangle with 3:4 aspect ratio.

**Comment by Vatsal2054** [comment]
@soni-shashan The highest level I can give is level 3.

**Comment by soni-shashan** [comment]
@Vatsal2054 kindly review

**Comment by Vatsal2054** [comment]
@soni-shashan This is the first level-3 PR of this repo. Congrats 🎉🎉.

**Pull request merged**
