### PR TITLE
Added Required Components

### PR DESCRIPTION
**Pull request by nandit27**
I have added the components as per your requirements and also I needed to add some code in the js file as when you press enter the data will be displayed so this part is implemented using js. Please review it and suggest changes if any.

### CODE REVIEW

**Comment by Vatsal2054** [comment]
## Next steps
This component must be stored in a different HTML file. Your previous design was for the landing page. Javascript is not needed as another contributor is working on that. 
- Store this component in a new HTML file (e.g. info_page.html, etc.)
- Make sure each info displaying field has a unique ID for easier access through javascript.
- Keep the landing page design as it is.
- Make sure you empty out the javascript file before pushing.

And then you are good to go. Inform me as soon as you complete the work :)

**Comment by nandit27** [comment]
I didn't understand what you are trying to convey.

**Comment by nandit27** [comment]
@Vatsal2054 I have cleared the JS File and created a new file for the weather information. Please review it.

**Comment by Vatsal2054** [comment]
Done!!

**Comment by nandit27** [comment]
@Vatsal2054 can you please add the hacktober-accepted tag to this PR so it is visible on the official website of HacktoberFest 2024 ?

**Pull request merged**
