### PR TITLE
Weather Report Card UI

### PR DESCRIPTION
**Pull request by PriyanshuValiya**
Screenshot 2024-10-18 224342

### CODE REVIEW

**Comment by PriyanshuValiya** [comment]
You can check weather on your current location and by searching cities.

**Comment by Vatsal2054** [comment]
### Nice work on javascript logic!!
Now, we have already got landing page UI and is merged into the main branch. You just need to edit your javascript to work with the new UI.
### Next steps:
- Pull the new changes from the main branch. Remember to delete your work in index.html and style.css before you fetch the new changes to avoid conflicts.
- Modify the javascript such that it works well with the landing page UI.
- Push the changes and let me know.

**Comment by PriyanshuValiya** [comment]
Is this ready to raise PR, as you told i have not worked on UI. If you say I will work on it, else i am raising PR..

Screenshot 2024-10-19 213603

**Comment by Vatsal2054** [comment]
Fetch the current changes from main branch and make sure your javascript works with the UI. The weather_info.html has been merged in the main branch.
- Landing page is the first entry point. Collect user location from the landing page using input field or using GPS. 
- Once the location is available, fetch the weather data from any open source API.
- Redirect user to weather_info.html and display weather info in that page.

Reference:
- [Redirecting User](https://stackoverflow.com/questions/4744751/how-do-i-redirect-with-javascript)

**Pull request closed without merging**
