### PR TITLE
Feat/Graph add

### PR DESCRIPTION
**Pull request by PriyanshuValiya**
**Page Preview**
Screenshot 2024-10-27 200841

### CODE REVIEW

**Comment by PriyanshuValiya** [comment]
@Vatsal2054 Why Forecast Card are hardcoded, means why it is not  set according API data ??

**Comment by Vatsal2054** [comment]
@PriyanshuValiya The forecast cards are not hard-coded. Check out the hosted website.

**Comment by PriyanshuValiya** [comment]
@Vatsal2054 Okay, please merge my changes if you like..

**Comment by Vatsal2054** [comment]
@PriyanshuValiya Nice work! Can you try to reduce the amount of labels in the x-axis of graph. Try to replace the datetime with weekdays or Just date if possible.

**Comment by PriyanshuValiya** [comment]
**Page Update**
Screenshot 2024-10-28 151232

**Comment by Vatsal2054** [comment]
@PriyanshuValiya Great work!!

**Pull request merged**
