### PR TITLE
Fix Issue.. #93

### PR DESCRIPTION
**Pull request by Meetpidev**
Fix Issue.. #93

### CODE REVIEW

**Comment by Meetpidev** [comment]
@Vatsal2054 Review PR..

**Comment by Vatsal2054** [comment]
@Meetpidev Can you explain your work? I am merging from my mobile so I am not able to review it.😅

**Comment by Meetpidev** [comment]
@Vatsal2054 Recently you merged PR.. But in that "weather.html" is different... thats why its not displying..

**Comment by Meetpidev** [comment]
@Vatsal2054 Requested to Review all the changes in other PRs and then after merged it...

**Comment by Meetpidev** [comment]
@Vatsal2054 Also Index.js file is different.. 
Screenshot 2024-10-31 212026
Screenshot 2024-10-31 212041
Screenshot 2024-10-31 212049

### Look at the provided image that you merged By previous PR.. he removed all my changes... that accepted by you....

**Comment by Meetpidev** [comment]
@Vatsal2054 you created more issues by merging previous PR.. In website see change of rain section.. there is no title of like "Chance of rain: --" there is Only % display.. and that is also wrong % ...

**Comment by Meetpidev** [comment]
@Vatsal2054 Can I raise The PR aging ?? that resolved all these problem ??

**Comment by Meetpidev** [comment]
@Vatsal2054 Should I raised PR ??

**Comment by Vatsal2054** [comment]
@Meetpidev Yes but last PR.

**Comment by Vatsal2054** [comment]
Make sure everything works. I don't want to mess up the site at last moment.

**Pull request closed without merging**
