### PR TITLE
JS Logic Added

### PR DESCRIPTION
**Pull request by PriyanshuValiya**
Final Output..

Screenshot 2024-10-20 133056

### CODE REVIEW

**Comment by Vatsal2054** [comment]
The 5-day forecast will have weather info for each day for the next 5 days. Is it possible to fetch that data?

**Comment by PriyanshuValiya** [comment]
Is Open Weather API provide this data ?

**Comment by Vatsal2054** [comment]
Open weather API provides forecast functionality for next 8 days.

**Comment by PriyanshuValiya** [comment]
I got data for next 5 days from API now, are you want to add that in graph
form or in simple text form ??

**Comment by PriyanshuValiya** [comment]
I got data for next 5 days from API now, are you want to add that in graph form or in simple text form ??

**Comment by Vatsal2054** [comment]
Store the 5 day forecast info in a javascript object for now. You would need to update it once the UI for forecast cards is completed.
Just clear out the HTML in the forecast section and we are good to go.

**Comment by PriyanshuValiya** [comment]
Is this ready to raise PR..

Screenshot 2024-10-20 173628

**Comment by Vatsal2054** [comment]
Well done👍🏻

**Comment by PriyanshuValiya** [comment]
Thank @Vatsal2054

**Comment by PriyanshuValiya** [comment]
Now, you want to implement graph visualizer for the forecast ?

**Comment by Vatsal2054** [comment]
You can work on it if you want but I think you should wait for the forecast cards to be completed. Two people working on same file will create conflicts.

**Comment by PriyanshuValiya** [comment]
Okay

**Comment by nandit27** [comment]
@PriyanshuValiya bro the web app is not working in my system. can you please help me with it ?
Screenshot 2024-10-22 at 5 46 18 PM
I added some logs and checked everything seems fine but the data is not being displayed and one error is also being shown in the console. 
@Vatsal2054 if u can help in this if possible

**Comment by PriyanshuValiya** [comment]
@nandit27 Recently I tried on my mobile and it's working completely, have you done some changes on your local system?

**Comment by nandit27** [comment]
I have not done any changes.

**Comment by PriyanshuValiya** [comment]
@nandit27 I think you have to connect both html files to script file..

**Comment by PriyanshuValiya** [comment]
Try it on your mobile one time..

**Comment by nandit27** [comment]
both of the html files have script tag where it is connected to the js file

**Comment by Vatsal2054** [comment]
The hosted website works fine. Make sure you have fetched the updated code.

**Comment by nandit27** [comment]
@Vatsal2054 Not only me it is not working for others also.

**Comment by Vatsal2054** [comment]
You all try entering city names like Ahmedabad, Rajkot, etc.

**Comment by nandit27** [comment]
Hosted Website

**Pull request merged**
