### PR TITLE
Placed Cards Currectly..

### PR DESCRIPTION
**Pull request by Meetpidev**
image

### CODE REVIEW

**Comment by Meetpidev** [comment]
@Vatsal2054 Requested to Review PR...

**Comment by Vatsal2054** [comment]
@Meetpidev This is already done. See deployed website.

**Comment by Meetpidev** [comment]
@Vatsal2054 In that doesnt need to display title that this is air quality and this is UV index.. because we already mentioned it before discription... just see in that image..

**Comment by Vatsal2054** [comment]
Just remove the title. Keep the separate cards as it is.

**Comment by Meetpidev** [comment]
@Vatsal2054 I already Removed it.. just see the following image that i commented here.. ill send PR again because this PR has Conflicts..

**Comment by Vatsal2054** [comment]
@Meetpidev It is just visually good to have two separate cards. Otherwise whole page will look like a stack of cards.

**Pull request closed without merging**
