### PR TITLE
Display error messages on the weather search page

### LINKED ISSUE #29: enhancement: instead of alert when city not found, implement ui page or ui element to show the error.

### PR DESCRIPTION
**Pull request by Uvesh99**
# Description
-Added an error message display in the search form of index.html to notify users when a city is not found or the input is invalid.
-Error messages now appear on the page instead of using alert(), providing a better user experience.
-Refactored the existing error handling in getWeatherByCity and getForecastByCity to show error messages in the newly added "div".
-This update improves the UI by removing disruptive alert popups and replacing them with inline messages.

Fixes #29

# Testing
- Manually tested by entering both valid and invalid city names.
- Verified that the error message is correctly displayed and that valid weather data loads properly when the city is found.

image

### CODE REVIEW

**Comment by Vatsal2054** [comment]
The PR has merge conflicts. Can you pull current changes and raise a PR again?

**Comment by Meetpidev** [comment]
@Vatsal2054 Is it still an issue ??

**Comment by Vatsal2054** [comment]
@Meetpidev Yes but let him work on that.

**Comment by Vatsal2054** [comment]
@Uvesh99 Can you raise this PR again?

**Pull request closed without merging**
